# Generated by Django 4.1.1 on 2022-10-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Elaqe', 'verbose_name_plural': 'Elaqeler'},
        ),
    ]
