# Generated by Django 4.1.1 on 2022-10-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_at',), 'verbose_name': 'Elaqe', 'verbose_name_plural': 'Elaqeler'},
        ),
    ]
