# Generated by Django 4.1.1 on 2022-10-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('created_at',), 'verbose_name': 'Resept', 'verbose_name_plural': 'Reseptler'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/story')),
                ('cover_image', models.ImageField(upload_to='media/story')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'verbose_name': 'Hekaye',
                'verbose_name_plural': 'Hekayeler',
                'ordering': ('created_at',),
            },
        ),
    ]
