# Generated by Django 4.1.1 on 2022-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_catagory_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(upload_to='catagory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(upload_to='recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(upload_to='story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='story'),
        ),
    ]
